version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: kintec
    container_name: -1
    env_file:
      - .env
    ports:
      - "3000:3000"